# Generated by Django 5.0.7 on 2024-07-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EuphoricApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_slug',
        ),
    ]
