# Generated by Django 5.0.7 on 2024-07-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EuphoricApp', '0004_product_delete_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_slug',
        ),
    ]
