# Generated by Django 5.0.7 on 2024-07-20 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EuphoricApp', '0005_remove_product_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.PositiveIntegerField(default=1)),
                ('order_email', models.EmailField(max_length=254)),
                ('order_phone', models.CharField(max_length=15)),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EuphoricApp.product')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
