# Generated by Django 5.0.7 on 2024-07-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EuphoricApp', '0007_alter_order_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
