# Generated by Django 5.0.7 on 2024-07-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EuphoricApp', '0008_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formContact_name', models.CharField(blank=True, max_length=250, null=True)),
                ('formContact_surname', models.CharField(blank=True, max_length=250, null=True)),
                ('formContact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('formContact_comment', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_title',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default=0.0, max_length=255),
        ),
    ]
